services:
  app:
    build: .
    container_name: endobot
    ports:
      - "3000:3000"  # Expose port 3000 on the host
    env_file:
      - .env  # Load environment variables
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface  # Persist transformer cache path
    volumes:
      - .:/usr/src/app  # Sync code changes in real-time
      - /usr/src/app/node_modules  # Prevent overwriting node_modules inside container
    restart: always  # Restart if the container crashes
