version: '3'
services:
  app:
    build: .
    container_name: endobot
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    env_file:
      - .env  # Load environment variables from a .env file
    volumes:
      - /var/www/endobot:/usr/src/app  # Sync the project folder with the container
    restart: always  # Ensure the container restarts if it crashes or the droplet reboots
